version: '3.8'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.5.3
    container_name: elasticsearch
    healthcheck:
      test: ["CMD-SHELL", "curl --silent --fail localhost:9200/_cluster/health || exit 1"]
      interval: 5s
      retries: 15
    ports:
      - "9200:9200"
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms256m -Xmx256m"
    volumes:
      - elasticsearch:/usr/share/elasticsearch/data

  kibana:
    image: docker.elastic.co/kibana/kibana:8.5.3
    container_name: kibana
    healthcheck:
      test: [ "CMD-SHELL", "curl --silent --fail localhost:5601 || exit 1" ]
      interval: 5s
      retries: 15
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    depends_on:
      elasticsearch:
        condition: service_healthy
        
  logs-worker:
    container_name: logs-worker
    image: logs-worker
    build:
      context: .
      dockerfile: logs-worker/Dockerfile
    volumes:
      - ${LOGS_FOLDER}:/logs-folder:ro
    environment:
      DOTNET_ENVIRONMENT: Development
    depends_on:
      elasticsearch:
        condition: service_healthy
      kibana:
        condition: service_healthy

volumes:
  elasticsearch: