services:
  seq:
    image: datalust/seq:latest
    container_name: seq
    ports:
      - "8080:80"
    environment:
      - ACCEPT_EULA=Y
    volumes:
      - seq:/data

  logs-worker:
    container_name: logs-worker
    image: logs-worker
    build:
      context: .
      dockerfile: logs-worker/Dockerfile
    volumes:
      - ${LOGS_FOLDER}:/logs-folder:rw
    depends_on:
      - seq

volumes:
  seq: